version: "2.1"

services:
    cms-xmr:
        image: xibosignage/xibo-xmr:release-0.8
        ports:
            - "9505:9505"
        restart: always
        env_file: config.env
        mem_limit: 256m
    cms-web:
        image: xibosignage/xibo-cms:release-2.3.6
        volumes:
            - "./shared/cms/custom:/var/www/cms/custom:Z"
            - "./shared/backup:/var/www/backup:Z"
            - "./shared/cms/web/theme/custom:/var/www/cms/web/theme/custom:Z"
            - "./shared/cms/library:/var/www/cms/library:Z"
            - "./shared/cms/web/userscripts:/var/www/cms/web/userscripts:Z"
            - "./shared/cms/ca-certs:/var/www/cms/ca-certs:Z"
        restart: always
        links:
            - cms-xmr:50001
        environment:
            - XMR_HOST=cms-xmr
        ports:
            - "80:80"
        env_file: config.env
        mem_limit: 1g
    cms-quickchart:
      image: ianw/quickchart
      restart: always
